- src/controllers/index.js
- src/controllers/playlists/api-doc.js
- src/controllers/playlists/index.js
- src/controllers/playlists/routes/apiDocs.js
- src/controllers/playlists/routes/index.js
- src/controllers/playlists/routes/{id}.js
- src/controllers/user/index.js
- src/controllers/user/playlists/api-doc.js
- src/controllers/user/playlists/index.js
- src/controllers/user/playlists/routes/apiDocs.js
- src/controllers/user/playlists/routes/index.js
- src/controllers/user/playlists/routes/{id}/cover.js
- src/controllers/user/playlists/routes/{id}/index.js
- src/controllers/user/playlists/routes/{id}/items/add.js
- src/controllers/user/playlists/routes/{id}/items/index.js
- src/controllers/user/playlists/routes/{id}/items/remove.js
- src/controllers/user/playlists/routes/{id}/privacy.js
- src/db/legacy/mysql-migrations.js
- src/db/migrations/20191017210551-playlist.js
- src/db/migrations/20191017210557-playlist_item.js
- src/db/models/index.js
- src/db/models/resonate/playlist.js
- src/db/models/resonate/playlist_item.js
Initial pass at adding a Playlist model that replaces the TrackGroup model for user playlists. 
Closes #67
> feat: add Playlist model

- src/config/swagger.js
- src/db/seeders/trackgroup-seeder.js
> chore: add migration plays and listener user.

- .env.example
- docker-compose.yml
- src/auth/redis-adapter.js
- src/controllers/user/admin/queues.js
- src/controllers/user/authenticate.js
- src/controllers/user/earnings.js
- src/jobs/convert-image.js
- src/jobs/create-report.js
- src/jobs/reprocess-track.js
This makes it so that we start redis with a password by default, and fixes all instances of it not using the full config.
> chore: clean up redis authentication error. closes #61

- test/Admin.ts/Trackgroups.test.js
- test/Admin.ts/Tracks.test.js
- test/Admin.ts/Users.test.js
- test/Api.ts/Artists.test.js
- test/Api.ts/Labels.test.js
- test/Api.ts/Search.test.js
- test/Api.ts/Tag.test.js
- test/Api.ts/Trackgroups.test.js
- test/Api.ts/Tracks.test.js
- test/Template.test.js
- test/User.ts/MiscUserInfo.test.js
- test/User.ts/Products.test.js
- test/User.ts/User.test.js
- test/User.ts/UserArtist.test.js
- test/User.ts/UserPlays.test.js
- test/User.ts/UserTracks.test.js
needed to add /* eslint-env mocha */ to top of all test files, in order to get standard plug-in 'onSave' to work.
> chore: added /* eslint-env mocha */ to make standard onSave work locally

- docker-compose.yml
- src/db/legacy/README.md
- src/db/legacy/pg-migrations.js
- src/db/seeders/trackgroup-seeder.js
> chore: add SSH to docker to facilitate migration of old databases

- README.md
- src/config/cors.js
- src/controllers/user/authenticate.js
- src/db/migrations/202207140053-client.js
- src/db/models/resonate/client.js
- src/db/seeders/clients-seeder.js
- src/index.js
> fix: refer to client CORS endpoints

- .env.example
- docker-compose.yml
- src/controllers/artists/routes/index.js
- src/controllers/labels/routes/index.js
- src/controllers/labels/routes/{id}/albums.js
- src/controllers/labels/routes/{id}/index.js
- src/controllers/playlists/routes/index.js
- src/controllers/trackgroups/routes/{id}.js
- src/controllers/user/playlists/routes/index.js
- src/controllers/user/profile/routes/index.js
- src/db/models/resonate/user_group.js
- src/db/models/resonate/user_group_link.js
Just lots of fixes to a couple of things that make it so those endpoints actually return meaningful data.
> fix: various endpoint fixes

- src/controllers/user/collection/routes/index.js
- src/controllers/user/favorites/routes/index.js
- src/controllers/user/plays/routes/stats.js
- src/scripts/reports/plays.js
- test/HowTheTestDataWasMade.md
- test/MockAccessToken.js
- test/README.md
- test/baseline/User.ts/MiscUserInfo.test.js
- Added requested edits / formatting to README.md (to clarify test data generation, other items)
- User.ts failed test count reduced from 9 to 5
Next step is to reduce User.ts fail count.
> feat: more fixes to user.ts tests and endpoints

- test/README.md
- test/baseline/User.ts/Products.test.js
- test/baseline/User.ts/UserArtist.test.js
- Reduced test fails by two
- Minor edit to README.md to point out where / why some tests are skipped.
> feat: more failed tests resolved, minor edit to readme.md file

- src/controllers/user/artists/routes/{id}/index.js
- src/controllers/user/trackgroups/routes/{id}/index.js
- test/baseline/Api.ts/Search.test.js
- test/baseline/User.ts/User.test.js
- test/baseline/User.ts/UserArtist.test.js
- Current fail count is now 0.
There's a lot more to be done with the tests, but this marks some sort of milestone.
> feat: repaired two endpoints. more passing tests

- .github/workflows/deploy-stage.yml
- .github/workflows/unit.yml
- .mocharc.js
- docker-compose.test.yml
- docker-compose.yml
- package.json
- src/controllers/user/artists/routes/index.js
- src/controllers/user/trackgroups/routes/index.js
- src/controllers/user/trackgroups/routes/{id}/index.js
- test/baseline/User.ts/User.test.js
- test/baseline/User.ts/UserArtist.test.js
- test/testConfig.js
- yarn.lock
This PR enables a unit test check that will automatically run for every future pull request. 
You can check the output by clicking on the "Details" button in the Review Required section of a PR. There it will tell you which tests passed, and which tests failed because of the changes you made. 
The tests are still a bit in flux but alongside the work @mattburnett-repo has been doing to straighten them out, they're slowly getting there and this will make sure that we don't merge breaking code into our codebase!
> feat: working github action unit tests

- src/db/legacy/mysql-migrations.js
- src/db/legacy/pg-migrations.js
- src/db/migrations/202207140053-user_group_member.js
- src/db/models/index.js
- src/db/models/resonate/client.js
- src/db/models/resonate/credit.js
- src/db/models/resonate/favorite.js
- src/db/models/resonate/image.js
- src/db/models/resonate/play.js
- src/db/models/resonate/playlist.js
- src/db/models/resonate/playlist_item.js
- src/db/models/resonate/role.js
- src/db/models/resonate/track_group.js
- src/db/models/resonate/track_group_item.js
- src/db/models/resonate/user.js
- src/db/models/resonate/user_group_member.js
> Various migration fixes

- test/README.md
- Left out an important word (one of the test commands). #derp
- Edited a sentence that was misleading / confusing.
> fix: corrected important typos

- src/config/cache.js
- src/controllers/user/authenticate.js
- src/index.mjs
> fix: pass tests cause they're cool

- src/db/seeders/test/trackgroup-seeder.js
- test/baseline/playlists/playlists.test.js
- test/baseline/user/MiscUserInfo.test.js
- test/baseline/user/UserPlays.test.js
Fix failing plays tests, but also add new playlist tests.
> test: fix failing tests

- src/db/models/resonate/user.js
This closes #147.
I think this is all that needs to happen for this?
> feat: default scope user model, hide sensitive info

- src/auth/utils.js
- src/controllers/api-doc.js
- src/controllers/playlists/services/playlistService.js
- src/controllers/trackgroups/routes/{id}.js
- src/controllers/tracks/services/trackService.js
- src/controllers/user/playlists/routes/index.js
- src/controllers/user/playlists/routes/{id}/index.js
- src/controllers/user/playlists/routes/{id}/items/index.js
- src/controllers/user/plays/routes/stats.js
- test/baseline/user/playlists.test.js
- test/baseline/user/trackgroups.test.js
User playlist tests to maintain feature parity.
> Playlist tests

- src/db/legacy/mysql-migrations.js
> fix: add script for migration descriptions

- README.md
- emails/new-upload/html.pug
- package.json
- src/controllers/user/trackgroups/routes/{id}/cover.js
- src/jobs/convert-audio.js
- src/jobs/queue-worker.js
- src/jobs/reprocess-track.js
- src/jobs/upload-b2.js
- src/util/process-file.js
- yarn.lock
This... was never working? But there is stuff _in_ backblaze. I'm very puzzled. But basically the library package we were using had notImplementedYet markers. 
Anyways, now it works.
> feat: enable backblaze uploading on production

- src/auth/routes.js
- src/controllers/user/playlists/routes/{id}/cover.js
- src/controllers/user/trackgroups/routes/{id}/cover.js
- src/controllers/user/tracks/routes/{id}/file.js
- src/jobs/optimize-image.js
- src/util/process-file.js
sendmail wasn't actually a worker. It was failing because it was an uncaught promise. So workers don't crash the server when they fail
closes #179
> fix: workers failing when uncaught promises, and sendmail await

- src/controllers/index.mjs
- src/controllers/user/products/routes/cancel.js
- src/controllers/user/products/routes/checkout.js
- src/controllers/user/products/routes/success.js
- src/controllers/webhooks/stripe_checkout_success.js
- src/db/legacy/mysql-migrations.js
more secure, but also adds the registration of listener subscriptions on purchase. 
closes #48
> feat: transition stripe success updates to happen via a webhook

- emails/email-confirmation/html.pug
- emails/email-confirmation/subject.pug
- emails/email-confirmation/text.pug
- emails/style.css
- src/controllers/api-doc.js
- src/controllers/user/products/routes/checkout.js
- src/controllers/user/profile/routes/index.js
- test/baseline/user/User.test.js
Users can reset their email addresses if they supply their passwords
TODO: Should also send an email to the old email address of the user.
> Email change confirmation

- src/controllers/api-doc.js
- src/controllers/artists/artistService.js
- src/controllers/index.mjs
- src/controllers/tracks/routes/index.js
- src/controllers/user/artists/routes/index.js
- src/controllers/user/artists/routes/{id}/image.mjs
- src/controllers/user/artists/routes/{id}/index.js
- src/db/models/resonate/file.js
- src/jobs/optimize-image.js
- src/util/process-file.js
- src/util/profile-image.js
- test/baseline/user/User.test.js
Adds the ability to upload banners and avatars for users.
> feat: allow uploading of user group banner and avatar images

- README.md
Including some basic steps that were required to run Docker, and therefore the application generally, on my Windows machine.
> chore: Additional setup requirements for Windows users
